To define a new ndarray, the easiest way is to use the array()

Creating Arrays

In [94]:
import numpy as np_antima

a = np_antima.array([1,2,3])
b = np_antima.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np_antima.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
print(a)
print("****************")
print(b)
print("*****************")
print(c)


[1 2 3]
****************
[[1.5 2.  3. ]
 [4.  5.  6. ]]
*****************
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [97]:
a_antima.ndim

1

In [98]:
b_antima.shape

(2, 3)

In [99]:
c_antima.size

12

In [100]:
c_antima.dtype

dtype('float64')

Initial Placeholders

In [103]:
np_antima.zeros((3,4))                     #Create an array of zeros

np_antima.ones((2,3,4),dtype=np.int16)     #Create an array of ones

d = np_antima.arange(10,25,5)              #Create an array of evenly spaces values

np_antima.linspace(0,2,9)                  #Create an array of evenly spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [106]:
e = np_antima.full((2,2),7)          #Create a constant array

f = np_antima.eye(2)                #Create a 2x2 identity matrix

np_antima.random.random((2,2))      #Create an array with random values

np_antima.empty((3,2))              #Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [110]:
#Type of Data

g_antima = np.array([['a','b'],['c','d']])
g_antima

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [111]:
g_antima.dtype

dtype('<U1')

In [112]:
g_antima.dtype.name

'str32'

In [113]:
f_antima = np.array([[1, 2, 3],[4, 5, 6]], dtype=complex)
f_antima

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [114]:
#Intrinsic Creation of an Array

np_antima.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
np_antima.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [116]:
# A feature that will be particularly useful is arange().
# This function generates Numpy arrays with numerical sequence that respond to particular rules depending on the passes arguments.

np_antima.arange(0, 10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np_antima.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

It is also possible to generate a sequence of values with precise intervals between them. If the third argument of the arange() function is specified, this will represent the gap between a value and the next one in the sequence of values.

In [33]:
np_antima.arange(0, 12, 3)

array([0, 3, 6, 9])

In [34]:
np_antima.arange(0, 6, 0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

So far you have only created one-dimensional arrays.

To generate two-dimensional arrays you can still continue to use the arange() function but combined with the reshape() function.

This function divides a linear array in different parts in the manner specified by the shape argument.

Another method to obtain arrays already containing values is to fill them with random values. This is possible using the random() function of the numpy.random module. This function will generate an array with many elements as specified in the argument.

In [118]:
np_antima.random.random(3)

array([0.15677471, 0.33179283, 0.18102804])

In [36]:
np_antima.random.random((3,3))

array([[0.1059483 , 0.89325777, 0.77823622],
       [0.45794668, 0.65406177, 0.76537859],
       [0.29158086, 0.75693619, 0.88863687]])

Basic Operations

In [119]:
a_antima = np.arange(4)
a_antima

array([0, 1, 2, 3])

In [38]:
a+4

array([4, 5, 6, 7])

In [39]:
a*2

array([0, 2, 4, 6])

In [120]:
b_antima = np.arange(4,8)
b_antima

array([4, 5, 6, 7])

In [121]:
print(a+b)
print("***********")
print(a-b)
print("*************")
print(a*b)
print("**********************")
print(a * np_antima.sin(b))
print("*************************")
print(a * np_antima.sqrt(b))

[[2.5 4.  6. ]
 [5.  7.  9. ]]
***********
[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
*************
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
**********************
[[ 0.99749499  1.81859485  0.42336002]
 [-0.7568025  -1.91784855 -0.83824649]]
*************************
[[1.22474487 2.82842712 5.19615242]
 [2.         4.47213595 7.34846923]]


In [122]:
# Moving on to the multidimensional case, even here the arithmetic operators continue to operate element-wise.
A_antima = np.arange(0, 9).reshape(3, 3)
print(A_antima)
print("*******************")
B_antima = np.ones((3, 3))
print(B_antima)
print("*******************")
print(A_antima * B_antima)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
*******************
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
*******************
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [123]:
#The Matrix Product

np_antima.dot(A,B)

array([[33., 33., 33.],
       [42., 42., 42.],
       [51., 51., 51.]])

In [124]:
A_antima.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [125]:
np_antima.dot(B,A)

array([[39., 42., 45.],
       [39., 42., 45.],
       [39., 42., 45.]])

In [126]:
# Increment and Decrement Operators

a_antima = np.arange(4)

a_antima

array([0, 1, 2, 3])

In [127]:
a_antima += 1
a_antima

array([1, 2, 3, 4])

In [128]:
a_antima -=1
a_antima

array([0, 1, 2, 3])

In [150]:
a_antima += 4
a_antima

array([14, 15, 16, 17, 18, 19])

In [151]:
a_antima *= 2
a_antima

array([28, 30, 32, 34, 36, 38])

Universal Functions(ufunc)
A universal function, generally called ufunc, is a function operating of an array in an element-by-element fashion.

This means that it is a function that acts individually on each single element of the input array to generate a corresponding result in a new output array.

At the end, you will obtain an array of the same size of the input.

There are many mathematical and trigonometric operations that meet this definition,

for example, the calculation of

the square root with sqrt(),

the logarithm with log(),

or the sin with sin().

In [62]:
a_antima = np.arange(1, 5)
a_antima

array([1, 2, 3, 4])

In [129]:
np_antima.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [130]:
np_antima.log(a)

array([0.        , 0.69314718, 1.09861229])

In [131]:
np_antima.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

Aggregate Functions

Aggregate functions are those functions that perform an operation on a set of values, an array for example, and produce a single result.

Therefore, the sum of all the elements in an array is an aggregate function.

Many functions of this kind are implemented within the class ndarray.

In [132]:
a_antima = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
a_antima

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [67]:
a_antima.sum()

15.0

In [68]:
a_antima.min()

0.3

In [69]:
a_antima.max()

5.7

In [70]:
a_antima.mean()

3.0

In [71]:
a_antima.std()

2.0079840636817816

Indexing, Slicing and Iterating

In [ ]:
Indexing

Array indexing always refers to the use of square brackets (‘[ ]’) to index the elements of the array so that it can then be referred individually for various uses such as extracting a value, selecting items, or even assigning a new value.

In [135]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [136]:
a[4]

14

In [75]:
a[-1]

15

In [76]:
a[-6]

10

In [77]:
# To select multiple items at once, you can pass array of indexes within the square brackets.

a[[1, 3, 4]]

array([11, 13, 14])

In [137]:
#Moving on to the two-dimensional case

#The values are two [row index, column index] 

A_antima = np.arange(10, 19).reshape((3, 3))
A_antima

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [152]:
A_antima[1, 2]

15

Slicing
Slicing is the operation which allows you to extract portions of an array to generate new ones.

Whereas using the Python lists the arrays obtained by slicing are copies, in NumPy, arrays are views onto the same underlying buffer.

Depending on the portion of the array that you want to extract (or view) you must make use of the slice syntax; that is, you will use a sequence of numbers separated by colons (‘:’) within the square brackets.

In [153]:
aIantima = np.arange(10, 16)
a_antima

array([28, 30, 32, 34, 36, 38])

In [81]:
a[1:5]

array([11, 12, 13, 14])

Now if you want to extract from the previous portion an item, skip a specific number of following items, then extract the next, and skip again ..., you can use a third number that defines the gap in the sequence of the elements between one element and the next one to take

In [139]:
a_antima[1:5:2]

array([11, 13])

In [140]:
a_antima[::2]

array([10, 12, 14])

In [141]:
a_antima[:5:2]

array([10, 12, 14])

In [142]:
a_antima[:5:]

array([10, 11, 12, 13, 14])

As regards the case of two-dimensional array, the slicing syntax still applies, but it is separately defined both for the rows and for the columns.

In [143]:
A_antima = np.arange(10, 19).reshape((3, 3))
A_antima

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [144]:
A_antima[0,:]

array([10, 11, 12])

In [145]:
A_antima[:,0]

array([10, 13, 16])

In [146]:
A_antima[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [147]:
A_antima[[0,2],0:2]

array([[10, 11],
       [16, 17]])

In [91]:
#Iterating an Array

for i in a:
  print(i)

10
11
12
13
14
15


In [148]:
for row in A_antima:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]


In [149]:
for item in A_antima.flat:
    print(item)

10
11
12
13
14
15
16
17
18
